import type { MethodologyEntry } from "@/domain/types";

/**
 * METHODOLOGY — catálogo rastreável de dados, indicadores, fórmulas, regras, interpretações e hipóteses.
 * Status:
 *  CONFIRMADO   — explícito numa fonte;
 *  INFERIDO     — implícito numa fonte (o sistema deduziu e explica como);
 *  EXPERIMENTAL — escolha do sistema para operacionalizar algo, sem respaldo metodológico;
 *  PENDENTE     — PENDENTE DE VALIDAÇÃO COM O PROFESSOR (não definido nas fontes).
 *
 * Nenhuma fonte disponível contém fórmula matemática explícita.
 */
const P1 = { documentId: "DOC-PARAMETROS", section: "1. Matriz Comparativa" };
const P2A = { documentId: "DOC-PARAMETROS", section: "2.A Dias e horários de pico" };
const P2B = { documentId: "DOC-PARAMETROS", section: "2.B Variações semanais, diárias e horárias" };
const P2C = { documentId: "DOC-PARAMETROS", section: "2.C Capacidade viária e nível de serviço" };
const E = (section: string) => ({ documentId: "DOC-ESPECIFICACAO", section });
const UFRJ = { documentId: "DOC-FLUXOS-UFRJ", section: "Relatórios de fluxo por faixa horária" };
const VEL = { documentId: "DOC-VELOCIDADES", section: "Velocidade média e 85º percentil" };

export const METHODOLOGY: MethodologyEntry[] = [
  // ---------------- DADOS ----------------
  {
    id: "M-FLUXO-OBS",
    name: "Fluxo veicular observado por intervalo",
    category: "DADO",
    description: "Contagem de veículos por faixa horária, por data, endereço, sentido e pista, conforme relatórios de fluxo.",
    formula: null,
    implementation: "Transcrição do valor do intervalo (ex.: '07:00–08:00 → 1.113'). Texto não numérico → AUSENTE.",
    variables: [{ symbol: "n_i", meaning: "Veículos no intervalo i", unit: "veíc" }],
    unit: "veic",
    purpose: "Dado primário que alimenta todos os indicadores temporais.",
    sources: [UFRJ, E("§3, §5")],
    externalSource: null,
    version: "0.2.0",
    status: "CONFIRMADO",
    gaps: ["Tabelas por faixa (lane) existem em parte dos locais; esta versão usa o total das faixas.", "Células vazias e zeros são registrados e não preenchidos."],
  },
  {
    id: "M-VELOCIDADE-OBS",
    name: "Velocidade média e 85º percentil reportados",
    category: "DADO",
    description: "Velocidade média por data/horário e 85º percentil, conforme o relatório de velocidades.",
    formula: null,
    implementation: "Campos averageSpeedKmh e p85SpeedKmh em TrafficObservation. Nenhum valor incorporado.",
    variables: [
      { symbol: "v̄_i", meaning: "Velocidade média no intervalo i", unit: "km/h" },
      { symbol: "V85_i", meaning: "85º percentil da velocidade no intervalo i", unit: "km/h" },
    ],
    unit: "km/h",
    purpose: "Observar como o tráfego se comporta, não só quantos veículos passam (especificação §7–8).",
    sources: [VEL, E("§7")],
    externalSource: null,
    version: "0.2.0",
    status: "CONFIRMADO",
    gaps: ["V85 é impresso por dia; em 2019 o mesmo valor se repete no mês inteiro (provável valor mensal).", "Na Linha Vermelha (05/2022) o V85 impresso é menor que a média — dado suspeito."],
  },
  {
    id: "M-MATRIZ",
    name: "Faixas reportadas na matriz comparativa",
    category: "DADO",
    description: "VDM, volume de fim de semana e picos por corredor/sentido, em faixas aproximadas (~mín – máx).",
    formula: null,
    implementation: "Transcrição + normalização (separador de milhar, '~', mín–máx). Nunca reduzidas a ponto médio.",
    variables: [],
    unit: null,
    purpose: "Caracterização comparativa dos corredores (DOC-PARAMETROS §1).",
    sources: [P1],
    externalSource: null,
    version: "0.2.0",
    status: "CONFIRMADO",
    gaps: ["Não se sabe se a faixa representa variação entre dias, entre equipamentos ou incerteza.", "Unidade grafada 'veg/dia' — interpretada como veículos."],
  },
  // ---------------- INDICADORES ----------------
  {
    id: "M-VDM",
    name: "Volume Diário Médio (VDM) — dias úteis",
    category: "INDICADOR",
    description: "Volume médio diário em dias úteis. Histórico: faixa transcrita da matriz. Séries: média de volumes diários completos.",
    formula: null,
    implementation: "VDM = (Σ V_d) / N, sobre dias úteis com 24 h completas. Dias incompletos são excluídos.",
    variables: [
      { symbol: "V_d", meaning: "Volume do dia útil d (24 h completas)", unit: "veíc/dia" },
      { symbol: "N", meaning: "Número de dias úteis completos", unit: "dias" },
    ],
    unit: "veic/dia",
    purpose: "Caracterizar o volume médio diário do corredor (§1) e comparar com fins de semana (§2.B).",
    sources: [P1, P2B],
    externalSource: null,
    version: "0.2.0",
    status: "INFERIDO",
    gaps: ["A fonte nomeia o indicador ('Volume Diário Médio') sem definir procedimento (quais dias, quantas semanas, dias incompletos). Média aritmética inferida do nome.", "Dias com hora vazia ou zerada e feriados ficam fora — critério do sistema."],
  },
  {
    id: "M-FLUXO-HORARIO",
    name: "Fluxo horário",
    category: "INDICADOR",
    description: "Veículos por hora. Nas séries UFRJ o intervalo já é de 1 h; para intervalos menores, soma dos intervalos da hora.",
    formula: null,
    implementation: "q_h = Σ n_i (intervalos válidos contidos na hora h); exige 60 min válidos, senão a hora fica sem valor.",
    variables: [
      { symbol: "n_i", meaning: "Contagem no intervalo i", unit: "veíc" },
      { symbol: "q_h", meaning: "Fluxo na hora h", unit: "veíc/h" },
    ],
    unit: "veic/h",
    purpose: "Base das análises de pico e de variação horária.",
    sources: [UFRJ, P1],
    externalSource: null,
    version: "0.2.0",
    status: "INFERIDO",
    gaps: ["Exigir 60 min válidos é critério do sistema."],
  },
  {
    id: "M-FLUXO-EQUIVALENTE",
    name: "Fluxo horário equivalente",
    category: "FORMULA",
    description: "Converte uma contagem em intervalo curto (ex.: câmera) em taxa horária.",
    formula: null,
    implementation: "q_eq = n · 60 / Δt   (Δt em minutos)",
    variables: [
      { symbol: "n", meaning: "Veículos contados no intervalo", unit: "veíc" },
      { symbol: "Δt", meaning: "Duração do intervalo", unit: "min" },
      { symbol: "q_eq", meaning: "Fluxo horário equivalente", unit: "veíc/h" },
    ],
    unit: "veic/h",
    purpose: "Separar o OBSERVADO (contagem) do CALCULADO (taxa) — especificação §33.",
    sources: [E("§33")],
    externalSource: null,
    version: "0.2.0",
    status: "INFERIDO",
    gaps: ["A especificação dá o exemplo '127 veículos → 1.524 veíc/h' sem informar o intervalo; 1.524 / 127 = 12, o que implica Δt = 5 min. Confirmar a fórmula e se há fator de pico."],
  },
  {
    id: "M-PICO",
    name: "Hora de pico e fluxo máximo",
    category: "INDICADOR",
    description: "Hora de maior fluxo no dia e dentro das janelas de pico da fonte.",
    formula: null,
    implementation: "q_pico = max(q_h); também restrito às janelas de M-JANELAS-PICO conforme o tipo de dia.",
    variables: [{ symbol: "q_pico", meaning: "Maior fluxo horário", unit: "veíc/h" }],
    unit: "veic/h",
    purpose: "Identificar os períodos de maior solicitação (§1, §2.A).",
    sources: [P1, P2A],
    externalSource: null,
    version: "0.2.0",
    status: "INFERIDO",
    gaps: ["A fonte não define se 'fluxo máximo' é hora cheia, hora móvel ou outro critério; as séries disponíveis são de hora cheia."],
  },
  {
    id: "M-VELOCIDADE-MEDIA",
    name: "Velocidade média agregada",
    category: "INDICADOR",
    description: "Velocidade média de um período a partir das médias por intervalo.",
    formula: null,
    implementation: "v̄ = Σ(n_i · v̄_i) / Σ n_i (ponderada pela contagem).",
    variables: [
      { symbol: "v̄_i", meaning: "Velocidade média no intervalo i", unit: "km/h" },
      { symbol: "n_i", meaning: "Contagem no intervalo i", unit: "veíc" },
    ],
    unit: "km/h",
    purpose: "Comparar velocidade e fluxo (especificação §8).",
    sources: [VEL, E("§7")],
    externalSource: null,
    version: "0.2.0",
    status: "PENDENTE",
    gaps: ["Agregação não definida na fonte (temporal × espacial; ponderação).", "Sem dados de velocidade."],
  },
  {
    id: "M-V85",
    name: "Velocidade do 85º percentil",
    category: "INDICADOR",
    description: "Velocidade abaixo da qual trafegam 85% dos veículos. O relatório de velocidades apresenta essa informação.",
    formula: null,
    implementation: "Exibido somente como valor reportado pela fonte. Não é recalculado nem agregado entre intervalos.",
    variables: [{ symbol: "V85", meaning: "85º percentil", unit: "km/h" }],
    unit: "km/h",
    purpose: "Caracterizar a distribuição de velocidades (especificação §7).",
    sources: [VEL, E("§7")],
    externalSource: null,
    version: "0.2.0",
    status: "CONFIRMADO",
    gaps: ["Sem valores. Agregar V85 de vários intervalos exigiria as velocidades individuais — não implementado."],
  },
  {
    id: "M-CAPACIDADE",
    name: "Capacidade viária",
    category: "INDICADOR",
    description: "A fonte cita 'capacidade teórica por faixa' e capacidade condicionada por interseções, agulhas e travessias, sem valores.",
    formula: null,
    implementation: "Parâmetro por segmento; indefinido (null).",
    variables: [{ symbol: "c", meaning: "Capacidade do segmento", unit: "veíc/h" }],
    unit: "veic/h",
    purpose: "Base para saturação e nível de serviço (§2.C); permite representar FLUXO + CAPACIDADE + INTERFERÊNCIAS (especificação §17).",
    sources: [P2C],
    externalSource: null,
    version: "0.2.0",
    status: "PENDENTE",
    gaps: ["Sem valor numérico nem método."],
  },
  {
    id: "M-SATURACAO",
    name: "Grau de saturação (v/c)",
    category: "FORMULA",
    description: "Razão fluxo/capacidade. A fonte usa 'saturação' apenas qualitativamente.",
    formula: null,
    implementation: "x = q / c — somente com c definido.",
    variables: [
      { symbol: "q", meaning: "Fluxo horário", unit: "veíc/h" },
      { symbol: "c", meaning: "Capacidade", unit: "veíc/h" },
    ],
    unit: "adimensional",
    purpose: "Possível base da condição operacional.",
    sources: [P2C],
    externalSource: "FONTE EXTERNA / NÃO PRESENTE NOS DOCUMENTOS — a razão v/c não aparece nas fontes.",
    version: "0.2.0",
    status: "PENDENTE",
    gaps: ["Depende de M-CAPACIDADE.", "Confirmar se v/c é o indicador desejado."],
  },
  // ---------------- REGRAS ----------------
  {
    id: "M-TIPO-DIA",
    name: "Tipo de dia (dia útil, sábado, domingo)",
    category: "REGRA",
    description: "A fonte distingue dias úteis (segunda a sexta), sábados e domingos.",
    formula: null,
    implementation: "datas do calendário de feriados/atípicos → FERIADO; seg–sex → DIA_UTIL; sáb → SABADO; dom → DOMINGO; sem data → DESCONHECIDO.",
    variables: [],
    unit: null,
    purpose: "Evitar tratar todos os dias com o mesmo padrão (especificação §11).",
    sources: [P2A, E("§11")],
    externalSource: null,
    version: "0.2.0",
    status: "CONFIRMADO",
    gaps: ["Calendário de feriados é FONTE EXTERNA (src/data/calendario.ts): Carnaval 2019 e 2022, Cinzas, 1º de maio."],
  },
  {
    id: "M-JANELAS-PICO",
    name: "Janelas de pico por tipo de dia",
    category: "REGRA",
    description: "Dias úteis: manhã 07–09 e tarde/noite 17–19. Sábado: concentração 11–15. Domingo: pico 16–19.",
    formula: null,
    implementation: "Tabela PEAK_WINDOWS (src/engine/series.ts). Usada para posicionar o pico observado e para a simulação.",
    variables: [],
    unit: null,
    purpose: "Referência temporal do estudo para análise de picos (§2.A).",
    sources: [P2A],
    externalSource: null,
    version: "0.2.0",
    status: "CONFIRMADO",
    gaps: ["São observações do estudo, não limites universais. Destaques por corredor (07–08 Américas/São Conrado e Linha Vermelha; 17–18 Américas/Santa Cruz e Abelardo Bueno) exibidos como citação."],
  },
  {
    id: "M-QUEDA-FDS",
    name: "Queda do VDM nos fins de semana (25–50%)",
    category: "REGRA",
    description: "Observação do estudo: a queda do VDM nos fins de semana varia de 25% a 50%, conforme a tipologia da via.",
    formula: null,
    implementation: "queda_mín = 1 − V_fds,máx / VDM_mín ; queda_máx = 1 − V_fds,mín / VDM_máx (aritmética de intervalos). Compatível se intersecta [25%, 50%].",
    variables: [
      { symbol: "VDM_mín, VDM_máx", meaning: "Faixa de VDM em dias úteis", unit: "veíc/dia" },
      { symbol: "V_fds,mín, V_fds,máx", meaning: "Faixa de volume de fim de semana", unit: "veíc/dia" },
    ],
    unit: "%",
    purpose: "Verificação de coerência entre §1 e §2.B — não é limite universal.",
    sources: [P2B, P1],
    externalSource: null,
    version: "0.2.0",
    status: "EXPERIMENTAL",
    gaps: ["A regra 25–50% está na fonte; a forma de calculá-la é escolha do sistema.", "'Tipologia da via' não definida."],
  },
  {
    id: "M-MADRUGADA",
    name: "Madrugada (01–05h) abaixo de 5% do pico",
    category: "REGRA",
    description: "Observação do estudo: entre 01:00 e 05:00 o fluxo cai aos níveis mínimos, geralmente abaixo de 5% do volume de pico; crescimento abrupto a partir das 06:00.",
    formula: null,
    implementation: "razão = max(q_h, 01h ≤ h < 05h) / max(q_h) ; exige as 4 horas; divergência registrada como SUSPEITO, nunca corrigida.",
    variables: [],
    unit: "%",
    purpose: "Visualizar e verificar o comportamento temporal (especificação §13).",
    sources: [P2B],
    externalSource: null,
    version: "0.2.0",
    status: "EXPERIMENTAL",
    gaps: ["'Geralmente' — padrão descritivo, não limite. Interpretação de 'volume de pico' como maior fluxo horário do dia é do sistema."],
  },
  {
    id: "M-COMPARACAO",
    name: "Comparabilidade entre períodos",
    category: "REGRA",
    description: "Não comparar períodos incompatíveis sem deixar isso explícito (especificação §31).",
    formula: null,
    implementation: "Comparável ⇔ mesmo segmento E mesmo tipo de dia conhecido. Caso contrário, a comparação é exibida com aviso.",
    variables: [],
    unit: null,
    purpose: "Evitar comparações enganosas entre dias úteis, sábados, domingos e locais diferentes.",
    sources: [E("§31")],
    externalSource: null,
    version: "0.2.0",
    status: "CONFIRMADO",
    gaps: ["Critério operacional (mesmo segmento + mesmo tipo de dia) é do sistema; diferenças de ano/mês são mostradas mas não bloqueiam."],
  },
  {
    id: "M-QA-ALTERNANCIA",
    name: "Heurística de qualidade — padrão alternado",
    category: "HIPOTESE",
    description: "Sinaliza séries cuja variação horária inverte de sentido repetidamente com grande amplitude — possível erro de transcrição/transposição.",
    formula: null,
    implementation: "≥ 3 inversões consecutivas de sinal de Δq, cada uma com |Δq| ≥ 20% do valor anterior → SUSPEITO.",
    variables: [],
    unit: null,
    purpose: "Qualidade de dados. Não é metodologia de tráfego e não altera valores.",
    sources: [],
    externalSource: "Parâmetros do sistema (3 inversões; 20%) — não presentes nos documentos.",
    version: "0.2.0",
    status: "EXPERIMENTAL",
    gaps: ["Parâmetros arbitrários; servem para priorizar conferência com o PDF."],
  },
  // ---------------- INTERPRETAÇÕES ----------------
  {
    id: "M-NIVEL-SERVICO",
    name: "Nível de Serviço (A–F)",
    category: "INTERPRETACAO",
    description: "A fonte cita 'Nível de Serviço E/F' na Linha Vermelha, sem critério.",
    formula: null,
    implementation: null,
    variables: [],
    unit: null,
    purpose: "Classificação citada em §2.C.",
    sources: [P2C],
    externalSource: null,
    version: "0.2.0",
    status: "PENDENTE",
    gaps: ["Sem medida de desempenho nem limites. Não implementado; exibido só como citação."],
  },
  {
    id: "M-RELACAO-FLUXO-VELOCIDADE",
    name: "Relação fluxo × velocidade",
    category: "INTERPRETACAO",
    description: "Conceito: fluxo ↑ com velocidade ↓ pode indicar deterioração operacional.",
    formula: null,
    implementation: "Somente visualização lado a lado (sem eixo duplo). Não gera classificação.",
    variables: [],
    unit: null,
    purpose: "Observar como o tráfego se comporta, não só quantos veículos há (especificação §8).",
    sources: [E("§8")],
    externalSource: null,
    version: "0.2.0",
    status: "PENDENTE",
    gaps: ["A especificação proíbe transformar a relação em fórmula ou classificação sem metodologia do professor."],
  },
  {
    id: "M-CONDICAO",
    name: "Condição operacional (NORMAL → ATENÇÃO → CRÍTICO → CONGESTIONADO)",
    category: "INTERPRETACAO",
    description: "Barra de condição exemplificada pelo professor. Indicador-base e limites não definidos.",
    formula: null,
    implementation: "nível = NORMAL se x < L1; ATENÇÃO se L1 ≤ x < L2; CRÍTICO se L2 ≤ x < L3; CONGESTIONADO se x ≥ L3. Sem L1..L3 → INDETERMINADO (não exibido como nível).",
    variables: [
      { symbol: "x", meaning: "Indicador-base (a definir)", unit: "—" },
      { symbol: "L1, L2, L3", meaning: "Limites entre níveis", unit: "—" },
    ],
    unit: null,
    purpose: "Transformar dados em condição operacional compreensível (especificação §19).",
    sources: [E("§19")],
    externalSource: null,
    version: "0.2.0",
    status: "PENDENTE",
    gaps: ["Limites aguardando validação metodológica.", "Indicador-base não definido."],
  },
  // ---------------- VISÃO COMPUTACIONAL ----------------
  {
    id: "M-CV-CONTAGEM",
    name: "Contagem por linha virtual (visão computacional)",
    category: "DADO",
    description:
      "Veículos detectados por YOLO e rastreados por ByteTrack são contados uma vez quando o centroide do rastro cruza um segmento de linha desenhado sobre a via; o sentido vem do lado de chegada.",
    formula: null,
    implementation:
      "cruzamento = segmentos [centroide(t−1), centroide(t)] e [P1, P2] se intersectam; sentido = sinal do produto vetorial (P2−P1)×(c−P1) após o cruzamento. Cada (rastro, linha) conta no máximo uma vez. Classe = classe mais frequente do rastro.",
    variables: [
      { symbol: "n", meaning: "Cruzamentos por linha e sentido no intervalo", unit: "veíc" },
      { symbol: "Δt", meaning: "Duração do intervalo analisado", unit: "s" },
    ],
    unit: "veic",
    purpose: "Produzir a camada OBSERVADO a partir de vídeo, no mesmo formato (CameraObservation) que uma câmera real usaria.",
    sources: [E("§20–21, §33")],
    externalSource: "FONTE EXTERNA / NÃO PRESENTE NOS DOCUMENTOS — Ultralytics YOLO (detecção) e ByteTrack (rastreamento); procedimento de linha virtual é escolha do sistema.",
    version: "0.3.0",
    status: "EXPERIMENTAL",
    gaps: [
      "Precisão não medida: falta contagem manual de referência.",
      "Trocas de ID do rastreador podem duplicar contagens; veículos ocultos podem não ser contados.",
      "Classes COCO (carro, moto, ônibus, caminhão) não correspondem a uma taxonomia validada.",
    ],
  },
  {
    id: "M-CV-ESTABILIZACAO",
    name: "Estabilização de vídeo e janela válida",
    category: "HIPOTESE",
    description:
      "Para vídeos com câmera não fixa, cada quadro é alinhado ao quadro de referência por homografia; a contagem para quando o alinhamento se perde ou quando uma linha sai do enquadramento.",
    formula: null,
    implementation: "ORB (4000 pontos) + RANSAC (3 px) → H quadro→referência; válido se inliers ≥ 300 e |escala − 1| ≤ 0,05 e todas as linhas visíveis.",
    variables: [],
    unit: null,
    purpose: "Garantir que as linhas de contagem representem sempre a mesma seção da via.",
    sources: [],
    externalSource: "FONTE EXTERNA / NÃO PRESENTE NOS DOCUMENTOS — técnica padrão de visão computacional (OpenCV); limites são parâmetros do sistema.",
    version: "0.3.0",
    status: "EXPERIMENTAL",
    gaps: ["Em câmeras fixas (caso de uso real) a estabilização é desnecessária."],
  },
  {
    id: "M-INTENSIDADE-RELATIVA",
    name: "Intensidade relativa ao histórico do local (barras do painel)",
    category: "HIPOTESE",
    description:
      "Régua visual do painel: o fluxo da hora dividido pelo maior fluxo horário já registrado no mesmo trecho; a velocidade da hora dividida pela maior velocidade média horária do trecho.",
    formula: null,
    implementation: "I_fluxo = q_h / max(q_h do trecho) ; I_vel = v̄_h / max(v̄_h do trecho). Cor contínua verde→vermelho, sem faixas nem limites.",
    variables: [
      { symbol: "q_h", meaning: "Fluxo na hora h do dia exibido", unit: "veíc/h" },
      { symbol: "max(q_h)", meaning: "Maior fluxo horário válido do trecho em todos os períodos", unit: "veíc/h" },
    ],
    unit: "%",
    purpose: "Comunicar visualmente quando o movimento está alto ou baixo para aquele local, sem inventar limites de congestionamento.",
    sources: [],
    externalSource: "Escolha de visualização do sistema; não é indicador da fonte. O máximo histórico não é a capacidade da via.",
    version: "0.4.0",
    status: "EXPERIMENTAL",
    gaps: ["Será substituída pela condição operacional oficial quando o professor definir indicador-base e limites (M-CONDICAO)."],
  },
  {
    id: "M-LOCALIZACAO-ENDERECO",
    name: "Busca de endereço e radar do estudo mais próximo",
    category: "REGRA",
    description:
      "O endereço digitado é localizado no cadastro público de Logradouros da Prefeitura (Data.Rio): nome do logradouro sem acento e número dentro da faixa de numeração do lado par ou ímpar. Os locais do estudo são ordenados pela distância em linha reta entre a coordenada impressa no relatório e o traçado do trecho.",
    formula: null,
    implementation: "trecho: completo LIKE nome ∧ np_ini ≤ n ≤ np_fin (lado conforme paridade de n) ; d = min distância ponto–segmento do traçado (haversine/aprox. plana local). Exibe os 3 locais mais próximos com a distância, sem limite de corte.",
    variables: [
      { symbol: "n", meaning: "Número do imóvel digitado", unit: "—" },
      { symbol: "d", meaning: "Distância do radar do estudo ao trecho encontrado", unit: "m" },
    ],
    unit: "m",
    purpose: "Atender ao fluxo pedido pelo professor (digitar o endereço → mapear a via → ligar ao equipamento de medição) com os dados que existem hoje.",
    sources: [],
    externalSource: "FONTE EXTERNA / NÃO PRESENTE NOS DOCUMENTOS: cadastro Trechos_Logradouros (IPP/Prefeitura do Rio, via Data.Rio), serviço aberto. Hierarquia viária e velocidade regulamentada vêm desse cadastro e não são capacidade.",
    version: "0.5.0",
    status: "EXPERIMENTAL",
    gaps: [
      "Não há critério documentado para dizer se um radar representa o tráfego de um endereço; o sistema só mostra a distância.",
      "Dados em tempo real dependem de acesso autorizado ao CIVITAS (cadastro /radars e contagens).",
    ],
  },
];

export function getMethodology(id: string): MethodologyEntry {
  const m = METHODOLOGY.find((x) => x.id === id);
  if (!m) throw new Error(`Metodologia desconhecida: ${id}`);
  return m;
}
